# ================================================================================================

PREFIX ex:   <http://example.org/smartcity#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX saref:<https://saref.etsi.org/core/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX sh:   <http://www.w3.org/ns/shacl#>

# Q18 · SCENARIO 8 — Restricted zone: internal node covers area
# Level   : Intermediate
# Scenario: 8
# ----------------------------------------------------------------
SELECT ?node ?zone ?zoneType ?connLabel ?opStatus ?resourcePct
WHERE {
  ?node ex:coversArea ?zone .
  ?zone a ?zoneType .
  ?zoneType rdfs:subClassOf* ex:CityArea .
  ?node ex:hasNodeState ?ns .
  ?ns ex:hasCommunication ?comm . ?comm rdfs:label ?connLabel .
  ?ns ex:hasOperationalStatus ?op . ?op rdfs:label ?opStatus .
  ?ns ex:resourceUsagePercent ?resourcePct .
  FILTER (?zoneType = ex:RestrictedZone)
}
