# ================================================================================================

# Políticas con zona declarada pero no enlazadas desde la zona mediante governedBy
# Expectativa: Incumplimiento. Debe devolver 0 filas.

PREFIX ex:   <http://example.org/smartcity#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX sh:   <http://www.w3.org/ns/shacl#>

SELECT ?policy ?zone
WHERE {
  ?policy a ex:Policy ;
          ex:appliesInZone ?zone .
  FILTER NOT EXISTS { ?zone ex:governedBy ?policy . }
}
ORDER BY ?zone ?policy

# ------------------------------------------------------------------------------------------------
