[layer]
tier = "edge"

[[nodes]]
id = "edge1"
device_type = "raspberry-pi-500"
host = "100.101.178.35"
endpoint = "http://100.101.178.35:8391"
local = false
port = 8391
authority = true

[nodes.resources]
cpu_cores = 4
cpu_architecture = "armv7l-32bit"
ram = "8g"
storage_mib = 32768
processing_capacity = 0.40
network_mbps = 100

[nodes.location]
region = "physical-lab"

[[nodes]]
id = "edge2"
device_type = "raspberry-pi-500"
host = "100.70.9.117"
endpoint = "http://100.70.9.117:8391"
local = false
port = 8391
authority = true

[nodes.resources]
cpu_cores = 4
cpu_architecture = "armv7l-32bit"
ram = "8g"
storage_mib = 32768
processing_capacity = 0.40
network_mbps = 100

[nodes.location]
region = "physical-lab"

[[nodes]]
id = "edge3"
device_type = "raspberry-pi-500"
host = "100.121.135.60"
endpoint = "http://100.121.135.60:8391"
local = false
port = 8391
authority = true

[nodes.resources]
cpu_cores = 4
cpu_architecture = "armv7l-32bit"
ram = "8g"
storage_mib = 32768
processing_capacity = 0.40
network_mbps = 100

[nodes.location]
region = "physical-lab"
