[layer]
tier = "fog"

[[nodes]]
id = "fog"
device_type = "raspberry-pi-500"
host = "10.151.73.241"
endpoint = "http://10.151.73.241:8391"
local = false
port = 8391
authority = false

[nodes.resources]
cpu_cores = 4
cpu_architecture = "armv7l-32bit"
ram = "2g"
storage_mib = 32768
processing_capacity = 0.45
network_mbps = 100

[nodes.location]
latitude = 0.0
longitude = 0.0
altitude_m = 0.0
region = "physical-lab"
