# ================================================================================================

PREFIX ex:   <http://example.org/smartcity#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX saref:<https://saref.etsi.org/core/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX sh:   <http://www.w3.org/ns/shacl#>

# Q14 · SCENARIO 4 — Find failed/degraded nodes and their cause
# Level   : Intermediate
# Scenario: 4
# ----------------------------------------------------------------
SELECT ?node ?opStatusLabel ?commLabel ?model ?degradCause
WHERE {
  ?node ex:hasNodeState ?ns .
  ?ns ex:hasOperationalStatus ?op .
  ?op rdfs:label ?opStatusLabel .
  ?ns ex:hasCommunication ?comm .
  ?comm rdfs:label ?commLabel .
  OPTIONAL {
    ?model ex:hostedOnNode ?node .
    ?model ex:hasDegradationCause ?dc .
    ?dc rdfs:label ?degradCause .
  }
  FILTER (?op IN (ex:ComputeOnly, ex:Inoperative))
}
