# ================================================================================================

PREFIX ex:   <http://example.org/smartcity#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX saref:<https://saref.etsi.org/core/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX sh:   <http://www.w3.org/ns/shacl#>

# Q12 · SCENARIO 2 — Detect saturated edges vs available fog
# Level   : Intermediate
# Scenario: 2
# ----------------------------------------------------------------
SELECT ?nodeType ?nodeLabel ?workloadLabel ?availLabel ?resourcePct
WHERE {
  ?node ex:hasNodeState ?ns .
  ?node rdfs:label ?nodeLabel .
  ?node a ?nodeType .
  ?nodeType rdfs:subClassOf ex:ComputationalNode .
  ?ns ex:hasWorkload ?wl . ?wl rdfs:label ?workloadLabel .
  ?ns ex:hasAvailability ?av . ?av rdfs:label ?availLabel .
  ?ns ex:resourceUsagePercent ?resourcePct .
  FILTER (?nodeType IN (ex:EdgeNode, ex:FogNode))
}
ORDER BY DESC(?resourcePct)
