# ================================================================================================

PREFIX ex:   <http://example.org/smartcity#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX saref:<https://saref.etsi.org/core/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX sh:   <http://www.w3.org/ns/shacl#>

# Q17 · SCENARIO 7 — Rural zone: verify retention conditions
# Level   : Intermediate
# Scenario: 7
# ----------------------------------------------------------------
SELECT ?userName ?zone ?connLabel ?batteryLabel ?dataReady ?profitability ?migTime
WHERE {
  ?user a ex:User .
  ?user foaf:name ?userName .
  ?user ex:locatedInZone ?zone .
  ?zone a ex:RuralZone .
  ?user ex:hasSemanticContract ?contract .
  ?contract ex:contractSubject ?user .
  ?user ex:hasWearable ?w .
  ?w ex:hasDeviceState ?ds .
  ?ds ex:hasConnectionStatus ?conn . ?conn rdfs:label ?connLabel .
  ?ds ex:hasBatteryLevel ?bat .     ?bat rdfs:label ?batteryLabel .
  ?ds ex:parametrizedDataReady ?dataReady .
  ?eval ex:auditsContract ?contract ;
        ex:hasProfitability ?prof ;
        ex:hasMigrationTime ?mt .
  ?prof rdfs:label ?profitability .
  ?mt rdfs:label ?migTime .
}
