#!/usr/bin/env python3
"""Install the reproducible coordinator-side OWL validation runtime.

Java reasoners are resolved from the pinned Maven POM. Konclude uses an
already-installed native binary when present; otherwise its official Docker
image is pulled. No validator is installed on physical workers.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
RUNTIME = ROOT / ".runtime"
CLASSPATH_FILE = RUNTIME / "owl-validation.classpath"
ENV_FILE = RUNTIME / "owl-reasoners.env"
KONCLUDE_IMAGE = "konclude/konclude"


def _run(command: list[str]) -> None:
    print("[owl-install] exec=" + shlex.join(command), flush=True)
    completed = subprocess.run(command, cwd=ROOT, check=False)
    if completed.returncode:
        raise RuntimeError(
            f"Command failed with exit code {completed.returncode}: "
            f"{shlex.join(command)}"
        )


def _require(name: str, hint: str) -> str:
    executable = shutil.which(name)
    if not executable:
        raise RuntimeError(f"{name} is required. {hint}")
    return executable


def install_java_reasoners() -> str:
    _require("java", "Install OpenJDK 17.")
    maven = _require("mvn", "Install Maven 3.8 or newer.")
    RUNTIME.mkdir(parents=True, exist_ok=True)
    _run(
        [
            maven,
            "-f",
            str(ROOT / "tools/owl/pom.xml"),
            "dependency:build-classpath",
            f"-Dmdep.outputFile={CLASSPATH_FILE}",
        ]
    )
    classpath = CLASSPATH_FILE.read_text(encoding="utf-8").strip()
    if not classpath:
        raise RuntimeError("Maven produced an empty OWL validation classpath")
    return classpath


def install_konclude(*, pull_image: bool) -> str:
    configured = os.environ.get("CONTINUUM_KONCLUDE_EXECUTABLE", "")
    native = configured or shutil.which("Konclude")
    if native:
        return f"native:{native}"
    if not pull_image:
        return "not-installed"
    docker = _require(
        "docker",
        "Install Docker or provide CONTINUUM_KONCLUDE_EXECUTABLE.",
    )
    _run([docker, "info"])
    _run([docker, "pull", KONCLUDE_IMAGE])
    return f"docker:{KONCLUDE_IMAGE}"


def write_environment(classpath: str, konclude: str) -> None:
    lines = [
        "# Generated by tools/install_owl_reasoners.py; do not commit.",
        f"export CONTINUUM_OWL_CLASSPATH={shlex.quote(classpath)}",
        f"export CONTINUUM_HERMIT_CLASSPATH={shlex.quote(classpath)}",
        f"export CONTINUUM_OPENLLET_CLASSPATH={shlex.quote(classpath)}",
        f"export CONTINUUM_JFACT_CLASSPATH={shlex.quote(classpath)}",
        f"export CONTINUUM_KONCLUDE_IMAGE={shlex.quote(KONCLUDE_IMAGE)}",
    ]
    if konclude.startswith("native:"):
        lines.append(
            "export CONTINUUM_KONCLUDE_EXECUTABLE="
            + shlex.quote(konclude.removeprefix("native:"))
        )
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--skip-konclude-image",
        action="store_true",
        help="Prepare Java reasoners but do not pull the Konclude Docker image",
    )
    args = parser.parse_args(argv)
    try:
        classpath = install_java_reasoners()
        konclude = install_konclude(
            pull_image=not args.skip_konclude_image
        )
        write_environment(classpath, konclude)
        print(f"[owl-install] classpath={CLASSPATH_FILE}")
        print(f"[owl-install] konclude={konclude}")
        print(f"[owl-install] environment={ENV_FILE}")
        print("[owl-install] ready; run: continuum-bench owl-validate --require-all")
        return 0
    except (OSError, RuntimeError) as error:
        print(f"[owl-install] ERROR: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
